# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [4]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [5]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.32064951 0.37664523 0.23498462 ... 0.04172174 0.63577554 0.84620411]
 [0.46290193 0.99645976 0.48294412 ... 0.2642919  0.2467543  0.42837872]
 [0.51997748 0.42749603 0.34398102 ... 0.22885567 0.55908448 0.2834241 ]
 ...
 [0.73584006 0.79392707 0.29704225 ... 0.21906672 0.99718039 0.86520182]
 [0.21903728 0.35626656 0.63371939 ... 0.85571578 0.28905753 0.02946069]
 [0.7033594  0.71607787 0.94699478 ... 0.42818451 0.87853981 0.76557055]]
[[0.87130353 0.31867567 0.68403895 ... 0.26114256 0.7044058  0.52560059]
 [0.57913722 0.2046189  0.13139735 ... 0.1644347  0.31882592 0.70213716]
 [0.75292682 0.53370771 0.26276484 ... 0.48315367 0.22446183 0.5710384 ]
 ...
 [0.43711767 0.19454685 0.05427424 ... 0.93246046 0.87529772 0.38918917]
 [0.50780366 0.10193585 0.69702337 ... 0.4638071  0.11205882 0.00653198]
 [0.4110157  0.75530105 0.85741151 ... 0.90370528 0.64111079 0.38921146]]


Без использования numpy

In [6]:
def mult(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

    # Перемножаем матрицы a и b и сохраняем результат в матрицу result.
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]

    return result

C использованием numpy

In [7]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [8]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.23 s, sys: 2.1 ms, total: 1.24 s
Wall time: 1.27 s


In [9]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 560 µs, sys: 4.1 ms, total: 4.66 ms
Wall time: 7.57 ms


In [10]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5351275806096965e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [11]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.57547077 0.12075742 0.18626362] [0.72019546 0.86305728 0.16994504]


In [12]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [13]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [15]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 21 µs, sys: 3 µs, total: 24 µs
Wall time: 27.4 µs
CPU times: user 45 µs, sys: 7 µs, total: 52 µs
Wall time: 55.1 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [16]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag_elements = np.diagonal(a)
  even_diag_elements = diag_elements[::2]
  res = np.sum(even_diag_elements)
  return res

In [17]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 6, 1, 9, 2],
       [6, 1, 4, 3, 9],
       [6, 2, 7, 7, 3],
       [5, 7, 9, 5, 5],
       [8, 8, 7, 1, 9]])

In [18]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 91 µs, sys: 14 µs, total: 105 µs
Wall time: 110 µs


24

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [20]:
from scipy import sparse
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = None

    # проверяем, является ли входная последовательность NumPy массивом или SciPy CSR матрицей
    if isinstance(A, np.ndarray):
        if A.ndim == 1:
            result = np.cumsum(A)
        else:
            result = np.apply_along_axis(np.cumsum, 1, A)
    elif isinstance(A, sparse.csr.csr_matrix):
        result = A.copy()
        result.data = np.cumsum(result.data)

    return result

In [21]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[5.18121644e-01 6.44329607e-01 7.53514863e-01 1.90313595e-01
 7.71535340e-01 1.39031507e-01 8.73844418e-01 4.83751003e-01
 8.33771579e-01 4.77028134e-02 3.56099223e-01 8.83865490e-02
 1.10145100e-01 6.48743505e-02 2.77842591e-01 9.81143514e-01
 4.89679562e-01 6.49254904e-01 1.01077315e-02 5.32286945e-01
 3.26095482e-01 3.38015584e-02 6.40735703e-01 9.52400348e-01
 5.87024156e-01 7.93304284e-01 3.04955940e-01 5.93479161e-01
 3.19710509e-01 2.86586741e-01 4.29105357e-01 3.73884670e-02
 8.12787885e-01 5.26441849e-01 1.94901675e-01 7.93522471e-02
 9.78378340e-01 8.38384224e-01 6.98562218e-01 1.80201655e-02
 5.27100742e-01 3.59064099e-01 5.30484405e-01 6.08031654e-01
 4.56475080e-03 9.93620032e-01 1.75614230e-01 3.47380776e-01
 1.88799925e-01 8.81131380e-01 8.85500714e-01 1.59938010e-01
 4.04097261e-01 1.66781869e-02 3.85199324e-01 5.53285439e-02
 4.26906708e-01 9.65774136e-01 7.67191406e-01 5.14312736e-01
 1.48315044e-01 9.66932611e-01 3.01523928e-01 9.63056675e-01
 7.71329752e-01 1.592986

<ipython-input-20-6fc465aa66d7>:12: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  elif isinstance(A, sparse.csr.csr_matrix):


### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [22]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    encoded_array = []
    repetition_counts = []

    for key, group in groupby(a):
        encoded_array.append(key)
        repetition_counts.append(len(list(group)))

    return np.array(encoded_array), np.array(repetition_counts)


In [23]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 55.6 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [24]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    X = copy(X)
    transformed_X = np.empty_like(X)

    for i in range(X.shape[0]):
        if i % 2 == 0:
            transformed_X[i] = X[i] ** 3
        else:
            transformed_X[i] = a

    result = np.concatenate((transformed_X[::-1], X[::-1]))

    return result

In [25]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 855 µs, sys: 0 ns, total: 855 µs
Wall time: 783 µs
